import type { Metadata } from "next";
import { Nunito, PT_Serif } from "next/font/google";
import "intro.js/minified/introjs.min.css";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${ptSerif.variable} antialiased relative`}>
        <div className="texture" aria-hidden="true" />
        {children}
      </body>
    </html>
  );
}
